print(" CCCC      A      HH    HH")
print("C    C    A A     HH    HH")
print("C        A   A    HHHHHHHH")
print("C       AAAAAAA   HHHHHHHH")
print("C    C A       A  HH    HH")
print(" CCCC A         A HH    HH")
